---

- name: A10 CFW Config
  hosts: "{{ target | default('all') }}"
  connection: local
  vars:
    wan_iface_netmask: "{{ ( wan_iface_ipaddr + '/' + wan_network_prefix | string ) | ipaddr('netmask') }}"
    wan_network : "{{ ( wan_iface_ipaddr + '/' + wan_network_prefix | string ) | ipaddr('network') }}"
    lan_iface_netmask: "{{ ( lan_iface_ipaddr + '/' + lan_network_prefix | string ) | ipaddr('netmask') }}"
    lan_network: "{{ ( lan_iface_ipaddr + '/' + lan_network_prefix | string ) | ipaddr('network') }}"
  gather_facts: false
  tasks:

    - name: wait
      pause:
        minutes: 10

    - name: debug
      debug:
        msg:
          - "{{target}}"
          - "{{ansible_user}}"
          - "{{ansible_ssh_pass}}"

    - name: wait for readiness
      local_action:
        module: wait_for host={{ ansible_host }} port=22 connect_timeout=5 timeout=910 search_regex=OpenSSH

    - name: Generate Dependencies - Interface Config
      template:
         src: templates/a10_interface_config.py.j2
         dest: /tmp/a10_interface_config.py
      mode: 0777

    - name: Generate Dependencies - NAT Config
      template:
         src: templates/a10_nat_config.py.j2
         dest: /tmp/a10_nat_config.py
      mode: 0777

    - name: Generate Dependencies - Static Route Config
      template:
         src: templates/a10_static_route_config.py.j2
         dest: /tmp/a10_static_route_config.py
      mode: 0777


    - name: Generate Dependencies - Firewall Config_Allowed
      template:
         src: templates/a10_fw_permit_config.py.j2
         dest: /tmp/a10_fw_permit_config.py
      mode: 0777

    - name: Generate Dependencies - Firewall Config_Blocked
      template:
         src: templates/a10_fw_deny_config.py.j2
         dest: /tmp/a10_fw_deny_config.py
      mode: 0777

    - name: Wait for system to be available
      pause:
         minutes: 1

    - name: Execute Script - Interface Config
      shell: python /tmp/a10_interface_config.py

    - name: wait
      pause:
        minutes: 1

    - name: Execute Script - NAT Config
      shell: python /tmp/a10_nat_config.py

    - name: wait
      pause:
        minutes: 1

    - name: Execute Script - Static Route Ctonfig
      shell: python /tmp/a10_static_route_config.py

    - name: wait
      pause:
        minutes: 1

    - name: Execute Script - Firewall Config_Allowed
      shell: python /tmp/a10_fw_permit_config.py

    - name: wait
      pause:
        minutes: 1

    - name: Execute Script - Firewall Config_Blocked
      shell: python /tmp/a10_fw_deny_config.py
