eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
  instance:
    metadata-map:
      user:
        name: admin
        password: admin
keycloak:
  auth-server-url: https://auth.mano.ubiqube.com/auth
  credentials:
    secret: ed9aeb6d-3ea5-4392-bb22-835603cf3dfc
  enabled: true
  principal-attribute: preferred_username
  realm: bootadmin
  resource: app-admin
  ssl-required: external
  token-minimum-time-to-live: 30
  use-resource-role-mappings: true
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
    de:
      codecentric: INFO
    org:
      keycloak: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLoggingListener: INFO
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
server:
  port: 8761
spring:
  application:
    name: mano-eureka-registry
  boot:
    admin:
      context-path: /admin
  cloud:
    discovery:
      enabled: true
  jmx:
    enabled: true
  security:
    user:
      name: admin
      password: admin
